version: "3.4"

volumes:
    v-hashbrown-mongodb: ~
    v-hashbrown-storage: ~

networks:
    n-hashbrown: ~
    
services:
    node:
        image: node
        container_name: "hashbrown-node"
        ports:
            - "8080:8080"
        depends_on:
            - mongodb
        networks:
            - n-hashbrown
        restart: unless-stopped
        command: "node /opt/hashbrown-cms"
        environment:
            - MONGODB_HOST=mongodb
        volumes:
            - "./:/opt/hashbrown-cms"
            - "/etc/localtime:/etc/localtime:ro"

    mongodb:
        image: mongo
        container_name: "hashbrown-mongo"
        networks:
            - n-hashbrown
        restart: unless-stopped
        volumes:
            - "v-hashbrown-mongodb:/data/db"
            - "/etc/localtime:/etc/localtime:ro"
