FROM node:alpine

WORKDIR /usr/src/app

RUN apk add --update git
RUN git clone https://github.com/Putaitu/hashbrown-cms.git -b stable --single-branch --recursive .
RUN npm install --production

COPY ./config/* ./config/

EXPOSE 8080
        
CMD ["sh", "-c", "node hashbrown.js create-user u=tyra-hashbrown p=tyra1234! admin=true && node hashbrown.js"]
