# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v2
      with:
        cache: 'npm'
    - run: npm install
    
    # Runs a Black Duck rapid scan on pull requests
    - name: Run RAPID Black Duck security scan
      if: ${{github.event_name == 'pull_request'}}
      uses: jcroall/blackduck-scan-action@1
      continue-on-error: true
      with:
        url: ${{ secrets.BLACKDUCK_URL }}
        token: ${{ secrets.BLACKDUCK_API_TOKEN }}
        mode: rapid
        output: blackduck-output
          
    # Runs special workflow steps for pull requests
    - name: Run Black Duck Advanced Workflow
      if: ${{github.event_name == 'pull_request'}}
      uses: jcroall/blackduck-workflow-action@1
      with:
        url: ${{ secrets.BLACKDUCK_URL }}
        token: ${{ secrets.BLACKDUCK_API_TOKEN }}
        fixpr: true
        comment: true
        upgrademajor: true
        input: blackduck-output
        sarif: blackduck-sarif.json
      env:
        GITHUB_TOKEN: ${{ github.token }}
          
    - name: Upload SARIF file
      if: ${{github.event_name == 'pull_request'}}
      uses: github/codeql-action/upload-sarif@v1
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: blackduck-sarif.json
